# Site settings
title: PompeyBUG
email: admin@pompeybug.org.uk
description: Your voice for a cycle-friendly Portsmouth.
baseurl: ""
url: "http://pompeybug.co.uk"
twitter_username: pompeybug

paginate: 10
paginate_path: "/news/page:num/"

# Extensions
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
markdown_ext: "markdown,md"

permalink: /:year/:month/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
